version: "3.8"

services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    web:
        build:
            context: ${PWD}
            dockerfile: docker/web/Dockerfile.production
        environment:
            FLASK_ENV: ${FLASK_ENV}
            FLASK_CONFIG: ${FLASK_CONFIG}
            APPLICATION_DB: ${APPLICATION_DB}
            POSTGRES_USER: ${APPLICATION_DB}
            POSTGRES_HOSTNAME: "db"
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_PORT: ${POSTGRES_PORT}
        command: gunicorn -w 4 -b 0.0.0.0 wsgi:app
        volumes:
            - ${PWD}:/opt/code
    nginx:
        image: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx.conf:ro
        ports:
            - 8080:8000
volumes:
    pgdata:
